/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tools.mapping;
import java.io.File;
import java.awt.image.BufferedImage;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Point;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.imageio.ImageIO;
/**
 *
 * @author Brandon
 */
public class MapMaker extends javax.swing.JFrame {
    static File file;
    static BufferedImage spritesheet;
    static String spritesheetFileLocation;
    static BufferedImage selectedTile;
    static int selectedTileX;
    static int selectedTileY;
    static int maxLayer;
    static int mapRow;
    static int mapCol;
    private static int scalex=1;
    private static int scaley=1;
    private static int gridSize=64;
    private static boolean tileErase=false;
    private static boolean entErase=false;
    /**
     * Creates new form MapMaker
     */
    public MapMaker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        toolbar = new javax.swing.JToolBar();
        newBtn = new javax.swing.JButton();
        loadBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        mapPanel = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                super.paintComponent(g);
                repaint();
                if(file!=null||spritesheet!=null||layerList.getSelectedValue()!=null){
                    g.setColor(new Color(64,64,64));
                    g.fillRect(0,0,mapCol*gridSize,mapRow*gridSize);
                    for(int i=0;i<=maxLayer;i++)
                    for(int r=0;r<mapRow;r++)
                    for(int c=0;c<mapCol;c++)
                    if(listModel.elementAt(i).get(r, c)!=0)
                    g.drawImage(spritesheet.getSubimage(gridSize*((listModel.elementAt(i).get(r,c)-1)%(spritesheet.getWidth()/gridSize)), gridSize*((listModel.elementAt(i).get(r,c)-1)/(spritesheet.getWidth()/gridSize)), gridSize,gridSize),c*gridSize,r*gridSize,null); 

                    g.setColor(Color.BLACK);
                    for(int r=0;r<layerList.getSelectedValue().rowSize+1;r++)
                    g.drawLine(0,r*gridSize,mapCol*gridSize,r*gridSize);
                    for(int c=0;c<layerList.getSelectedValue().colSize+1;c++)
                    g.drawLine(c*gridSize,0,c*gridSize,mapRow*gridSize);
                    Point pos = this.getMousePosition();
                    if(pos!=null&&insideGrid(pos)){
                        int r = (pos.y/gridSize)*gridSize;
                        int c = (pos.x/gridSize)*gridSize;
                        g.setColor(new Color(0,0,0,32));
                        g.fillRect(c, r, gridSize, gridSize);
                    }
                }
            }
        };
        tabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        spriteScrollPane = new javax.swing.JScrollPane();
        spriteSheetPanel = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                super.paintComponent(g);
                repaint();
                if(spritesheet!=null)
                g.drawImage(spritesheet,0,0,null);
                g.setColor(Color.BLACK);
                ((java.awt.Graphics2D)g).setStroke(new java.awt.BasicStroke(3));
                if(selectedTile!=null)
                g.drawRect(selectedTileX,selectedTileY,gridSize,gridSize);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        addLayerBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listModel = new DefaultListModel();
        layerList = new JList<Map>(listModel);
        tileEraseBtn = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        objModel = new DefaultListModel();
        objectList =  new JList<String>(objModel);
        objModel.addElement("Field");
        objModel.addElement("Inn");
        objModel.addElement("Npc");
        objModel.addElement("Portal");
        objModel.addElement("Shop");
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        entModel = new DefaultListModel<blade.Entity>();
        entitiyList = new JList<blade.Entity>(entModel);
        entEraseBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Winds Of Blade - Map Editor");
        setPreferredSize(new java.awt.Dimension(1280, 720));

        toolbar.setBorder(null);
        toolbar.setFloatable(false);
        toolbar.setRollover(true);

        newBtn.setText("New");
        newBtn.setFocusable(false);
        newBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });
        toolbar.add(newBtn);

        loadBtn.setText("Load");
        loadBtn.setFocusable(false);
        loadBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loadBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });
        toolbar.add(loadBtn);

        saveBtn.setText("Save");
        saveBtn.setFocusable(false);
        saveBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        toolbar.add(saveBtn);

        mapPanel.setFocusable(false);
        mapPanel.setName("mapPane"); // NOI18N
        mapPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mapPanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout mapPanelLayout = new javax.swing.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1334, Short.MAX_VALUE)
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 687, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(mapPanel);

        tabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPaneStateChanged(evt);
            }
        });

        jLabel2.setText("Sprite Sheet");

        spriteScrollPane.setToolTipText("");
        spriteScrollPane.setAutoscrolls(true);
        spriteScrollPane.setName("spritePane"); // NOI18N
        spriteScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                spriteScrollPaneMousePressed(evt);
            }
        });

        spriteSheetPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                spriteSheetPanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout spriteSheetPanelLayout = new javax.swing.GroupLayout(spriteSheetPanel);
        spriteSheetPanel.setLayout(spriteSheetPanelLayout);
        spriteSheetPanelLayout.setHorizontalGroup(
            spriteSheetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );
        spriteSheetPanelLayout.setVerticalGroup(
            spriteSheetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        spriteScrollPane.setViewportView(spriteSheetPanel);

        jLabel1.setText("Layers");

        addLayerBtn.setText("Add");
        addLayerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLayerBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Delete");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        layerList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(layerList);

        tileEraseBtn.setText("Eraser");
        tileEraseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tileEraseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spriteScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tileEraseBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addLayerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tileEraseBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spriteScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLayerBtn)
                    .addComponent(delBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Tiles", jPanel1);

        jLabel4.setText("Object List");

        objectList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(objectList);

        jLabel3.setText("Entities");

        entitiyList.setToolTipText("");
        jScrollPane2.setViewportView(entitiyList);

        entEraseBtn.setText("Eraser");
        entEraseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entEraseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(entEraseBtn))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entEraseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Entities", jPanel2);

        jSplitPane1.setLeftComponent(tabbedPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Map File","map");
        chooser.setFileFilter(filter);
        int value = chooser.showOpenDialog(this);
        if(value==JFileChooser.APPROVE_OPTION){
            file = chooser.getSelectedFile();
            try(BufferedReader br = new BufferedReader(new FileReader(file))){
                listModel.clear();
                gridSize = br.read();
                mapRow=br.read();
                mapCol=br.read();
                maxLayer=br.read();
                spritesheetFileLocation=br.readLine();
                try{
                    spritesheet = ImageIO.read(new File(spritesheetFileLocation));
                }catch(javax.imageio.IIOException e){
                    System.out.println("Cannot find SpriteSheet!");
                    //TODO Would you like relocate?
                }
                for(int i=0;i<=maxLayer;i++){
                    listModel.addElement(new Map(mapRow,mapCol,i));
                    for(int r=0;r<mapRow;r++)
                        for(int c=0;c<mapCol;c++)
                            listModel.elementAt(i).set(r,c,br.read());
                }
                layerList.setSelectedIndex(0);
            }catch(IOException e){
                e.printStackTrace();
            }
        }
    }                                       

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        NewForm nf = new NewForm(this, true);
        nf.setVisible(true);
    }                                      

    private void addLayerBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        maxLayer++;
        listModel.addElement(new Map(mapRow, mapCol, maxLayer));
    }                                           

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        listModel.remove(layerList.getSelectedIndex());
    }                                      

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        //gridSize, R, C, maxLayer, data:
        try(FileWriter fw = new FileWriter(file)){
            fw.write((char)gridSize);
            fw.write((char)mapRow);
            fw.write((char)mapCol);
            fw.write((char)maxLayer);
            fw.write(spritesheetFileLocation);
            fw.write('\n');
            for(int i=0;i<=maxLayer;i++)
                for(int r=0;r<mapRow;r++)
                    for(int c=0;c<mapCol;c++)
                        fw.write((char)listModel.elementAt(i).get(r, c));
            System.out.println("File Saved");
        }catch(IOException e){
            System.out.println("IO Error cannot find file "+file);
        }
    }                                       

    private void spriteScrollPaneMousePressed(java.awt.event.MouseEvent evt) {                                              

    }                                             

    private void mapPanelMousePressed(java.awt.event.MouseEvent evt) {                                      
        if(tabbedPane.getSelectedIndex()==0){
            if(tileErase)
                layerList.getSelectedValue().set((evt.getY()/gridSize),(evt.getX()/gridSize),0);
            else if(selectedTile!=null)
                layerList.getSelectedValue().set((evt.getY()/gridSize),(evt.getX()/gridSize),(selectedTileY/gridSize)*(spritesheet.getWidth()/gridSize)+(selectedTileX/gridSize)+1);
        }else if(tabbedPane.getSelectedIndex()==1){
            switch((String)objectList.getSelectedValue()){
                case "Field":
                        FieldForm f = new FieldForm(this,true,evt.getX()/gridSize,evt.getY()/gridSize);
                        f.setVisible(true);
                    break;
                case "Inn":
                    break;
                case "Npc":
                    break;
                case "Portal":
                    break;
                case "Shop":
                    break;
            }
        }
        
           // System.out.println(selectedTileY+","+selectedTileX+" "+((selectedTileY/gridSize)*(spritesheet.getWidth()/gridSize)+(selectedTileX/gridSize)));
           // System.out.println((selectedTileY/gridSize)+"*"+(spritesheet.getWidth()/gridSize)+"+"+(selectedTileX/gridSize));
        
       /* if(map!=null){
            for(int r=0;r<map.rowSize;r++){
                for(int c=0;c<map.colSize;c++){
                    System.out.print(map.get(r, c));
                }
                System.out.println("");
            }
        }*/
    }                                     

    private void spriteSheetPanelMousePressed(java.awt.event.MouseEvent evt) {                                              
        if(spritesheet!=null){
            selectedTileX = (evt.getX()/gridSize)*gridSize;
            selectedTileY = (evt.getY()/gridSize)*gridSize;
            selectedTile = spritesheet.getSubimage( selectedTileX, selectedTileY, gridSize, gridSize);
        }
    
    }                                             

    private void tileEraseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        tileErase=!tileErase;
    }                                            

    private void tabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {                                        
        switch(tabbedPane.getSelectedIndex()){
            case 0:
                tileErase=false;
                tileEraseBtn.setSelected(false);
                break;
            case 1:
                break;
        }
    }                                       

    private void entEraseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           
    private static boolean insideGrid(Point pos){
        return (pos.x>-1&&pos.x<layerList.getSelectedValue().colSize*gridSize&&pos.y>-1&&pos.y<layerList.getSelectedValue().rowSize*gridSize);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapMaker().setVisible(true);
            }
        });
    }
    static DefaultListModel<Map> listModel;
    static DefaultListModel<String> objModel;
    static DefaultListModel<blade.Entity> entModel;
    // Variables declaration - do not modify                     
    private javax.swing.JButton addLayerBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JToggleButton entEraseBtn;
    private javax.swing.JList<blade.Entity> entitiyList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    static javax.swing.JList<Map> layerList;
    private javax.swing.JButton loadBtn;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JButton newBtn;
    private javax.swing.JList objectList;
    private javax.swing.JButton saveBtn;
    private javax.swing.JScrollPane spriteScrollPane;
    static javax.swing.JPanel spriteSheetPanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JToggleButton tileEraseBtn;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration                   
}
